name: CD
on:
  workflow_run:
    workflows: [CI]
    branches: [main]
    types: [completed]

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: write
  pull-requests: write

jobs:
  publish:
    # when workflows: [CI] is success
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9.1.2
      - uses: actions/setup-node@v4
        with:
          node-version: 21.7.3
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      # when missed changesets in staging
      - name: Create Release Pull Request or Publish
        id: changesets
        uses: changesets/action@v1
        with:
          publish: pnpm run release
        env:
          # GITHUB_TOKEN is for changeset action
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Check if latest release
        id: check_tag
        run: echo "::set-output name=latest::$(pnpm info . dist-tags.latest)"

      - name: Tag the release if latest
        if: ${{ steps.check_tag.outputs.latest == github.sha }}
        run: |
          git tag -a release-latest -m "Release latest"
          git push origin release-latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
