name: CD

on:
  workflow_run:
    workflows: [CI]
    branches: [main]
    types: [completed]
  workflow_dispatch:

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: write
  pull-requests: write
  pages: write
  id-token: write

jobs:
  publish:
    # when workflows: [CI] is success
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9.1.2
      - uses: actions/setup-node@v4
        with:
          node-version: 21.7.3
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      # when missed changesets in staging
      - name: Create Release Pull Request or Publish
        id: changesets
        uses: changesets/action@v1
        with:
          publish: pnpm run release
        env:
          # GITHUB_TOKEN is for changeset action
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      
      # Generate docs only for full releases
      - name: Generate docs
        if: ${{ steps.changesets.outputs.published == 'true' }}
        run: pnpm run docs

      # Upload artifact only if docs were generated
      - name: Upload artifact
        if: ${{ steps.changesets.outputs.published == 'true' }}
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./sample-npm-package.github.io

  docs-deploy:
    needs: publish
    if: ${{ needs.publish.outputs.published == 'true' }}
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
