name: Pass Variables Between Jobs

on:
  push:
    branches:
      - main

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      job1-output: ${{ steps.set-output.outputs.result }}
    steps:
      - name: Set output variable
        id: set-output
        run: echo "::set-output name=result::Hello from Job 1"

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: Print output from Job 1
        run: echo "Output from Job 1: ${{ needs.job1.outputs.job1-output }}"
