name: Conditional Job Execution

on:
  push:
    branches:
      - main

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      condition: ${{ steps.set-condition.outputs.condition }}
    steps:
      - name: Set condition variable
        id: set-condition
        run: echo "::set-output name=condition::true" # Set to 'true' to run job2 or 'false' to skip job2

  job2:
    runs-on: ubuntu-latest
    needs: job1
    if: ${{ needs.job1.outputs.condition == 'true' }}
    steps:
      - name: Run if condition is true
        run: echo "Job 2 ran because the condition is true"

  job3:
    runs-on: ubuntu-latest
    needs: job1
    if: ${{ needs.job1.outputs.condition != 'true' }}
    steps:
      - name: Skip if condition is false
        run: echo "Job 3 skipped because the condition is false"
