name: Pass Variables Example

on:
  push:
    branches:
      - main

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      my_variable: ${{ steps.set_variable.outputs.my_variable }}
    steps:
      - name: Set Variable
        id: set_variable
        run: echo "::set-output name=my_variable::Hello from job1"
  
  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: Use Variable
        run: echo "Variable from job1: ${{ needs.job1.outputs.my_variable }}"
